antigen_file="${HOME}/.antigen/antigen.zsh"

if [ -f ${antigen_file} ] ; then
    source ${HOME}/.antigen/antigen.zsh
else
    echo "there is no antigen.zsh file in .antigen/"
fi

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell

# Tell antigen that you're done.
antigen apply
eval $(/usr/libexec/path_helper -s)

if [ -d "${HOME}/.cargo/bin" ] ; then
    export PATH="/Users/ion/.cargo/bin:${PATH}"
else
    echo "cargo is not installed"
fi

cargo_env_file="${HOME}/.cargo/env"
if [ -f ${cargo_env_file} ] ; then
    source ${cargo_env_file}
else
    echo "there is no .cargo/env file"
fi

echo "done"
