source ${HOME}/.antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell

# Tell antigen that you're done.
antigen apply
eval $(/usr/libexec/path_helper -s)

if [ -d "/Users/ion/.cargo/bin" ] ; then
    export PATH="/Users/ion/.cargo/bin:${PATH}"
fi
